version: "3.3"

services:
  mongo:
    image: "mongo:4.0.5"
    container_name: katana-mongo
    restart: always
    volumes:
      - "mongo-datadb:/data/db"
      - "mongo-configdb:/data/configdb"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.2
    container_name: katana-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zookeeper:2888:3888
        ZOOKEEPER_CLIENT_PORT: 2181
    restart: always
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-log:/var/lib/zookeeper/log
      - zk-secrets:/etc/zookeeper/secrets

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.4.2
    container_name: katana-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "slice:1:1"
    restart: always
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-secrets:/etc/kafka/secrets
    depends_on:
      - zookeeper

  katana-nbi:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-nbi:${DOCKER_TAG}"
    build:
      context: .
      dockerfile: katana-nbi/Dockerfile
    container_name: katana-nbi
    command: gunicorn -b 0.0.0.0:8000 --workers 3 --access-logfile - --reload "katana.app:create_app()"
    volumes:
      - "katana-prom-targets:/targets"
    ports:
      - "8000:8000"
    environment:
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    restart: always
    depends_on:
      - kafka
      - mongo
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "udp://10.30.0.245:5140"
    #     tag: "SliceManager"
    #     syslog-format: "rfc5424"

  katana-mngr:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-mngr:${DOCKER_TAG}"
    container_name: katana-mngr
    build:
      context: .
      dockerfile: katana-mngr/Dockerfile
    command: python3 katana/katana-mngr.py
    volumes:
      - "katana-grafana-templates:/katana-grafana/templates" 
    env_file:
      - "katana-mngr/.env"
      - "katana-grafana/.env" 
    restart: always
    depends_on:
      - katana-nbi
      - mongo
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "udp://10.30.0.245:5140"
    #     tag: "SliceManager"
    #     syslog-format: "rfc5424"

  katana-cli:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-cli:${DOCKER_TAG}"
    container_name: katana-cli
    build:
      context: .
      dockerfile: katana-cli/Dockerfile
    command: >
      /bin/bash
    stdin_open: true
    tty: true
    network_mode: "host"
    restart: always
    depends_on:
      - katana-nbi

  katana-swagger:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-swagger:${DOCKER_TAG}"
    container_name: katana-swagger
    build:
      context: .
      dockerfile: katana-swagger/Dockerfile
    restart: always
    environment:
      - SWAGGER_JSON=/my_swagger/swagger.json
    ports:
      - "8001:8080"
    depends_on:
      - katana-mngr

  # postgres:
  #   env_file:
  #     - "katana-ui/.env"
  #   image: "postgres:10.3-alpine"
  #   container_name: katana-postgres
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   volumes:
  #     - "postgres:/var/lib/postgresql/data"

  # katana-ui:
  #   build: ./katana-ui
  #   image: katana-ui
  #   container_name: katana-ui
  #   command: gunicorn -b 0.0.0.0:8080 --workers 3 --access-logfile - --reload "ui.app:create_app()"
  #   depends_on:
  #     - "postgres"
  #   env_file:
  #     - "katana-ui/.env"
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   volumes:
  #     - "./katana-ui:/app"
  #   depends_on:
  #     - katana-mngr
  #     - postgres

  katana-prometheus:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-prometheus:${DOCKER_TAG}"
    container_name: katana-prometheus
    build:
      context: .
      dockerfile: katana-prometheus/Dockerfile
    volumes:
      - "prometheus:/prometheus"
      - "katana-prom-targets:/etc/prometheus/targets"
    restart: unless-stopped
    ports: 
      - "9090:9090"

  katana-grafana:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-grafana:${DOCKER_TAG}"
    container_name: katana-grafana
    build:
      context: .
      dockerfile: katana-grafana/Dockerfile
    restart: unless-stopped
    ports: 
      - "3000:3000"
    env_file: katana-grafana/.env
    depends_on: 
      - katana-prometheus

  katana-nfv_mon:
    image: "${DOCKER_REG}${DOCKER_REPO}katana-nfv_mon:${DOCKER_TAG}"
    container_name: katana-nfv_mon
    build:
      context: .
      dockerfile: katana-nfv_mon/Dockerfile
    restart: unless-stopped
    env_file: 
      - "katana-grafana/.env"
      - "katana-nfv_mon/.env"
    command: >
      python katana/exporter.py
    ports:
      - "8002:8002"
    depends_on: 
      - katana-mngr
      - katana-grafana

volumes:
  mongo-datadb: {}
  mongo-configdb: {}
  postgres: {}
  zk-data: {}
  zk-log: {}
  zk-secrets: {}
  kafka-data: {}
  kafka-secrets: {}
  prometheus: {}
  katana-prom-targets: {}
  katana-grafana-templates: {}